### ISSUE TITLE
Instaloader is already doing what this library does

### ISSUE THREAD

**Issue by ogencoglu** [FKLC/IGQL#1]
Hi,

Documentation on what is different between this work and _instaloader_ (https://github.com/instaloader/instaloader) package would be appreciated.

**Comment by FKLC** [comment]
Well actually I have never seen this package before, but even If I, these libraries aren't same. I made a full search in instaloader to find 'graphql' but I can't found any even only this makes this library different. Also this library returns all data. IGQL isn't designed to be a CLI or a tool, it is a data collector GraphQL returns more data than a normal instagram page. For example in `media.data['accessibility_caption']` you can get what is in the image without running object detection.

**Comment by ogencoglu** [comment]
Thanks for the explanation. Cheers!

**Comment by FKLC** [comment]
I'm actually sorry about the response I made. I think I've searched for something else accidentally and the Instaloader library definitely uses GraphQL so this is the end of the library support since the Instaloader is much better than IGQL.

**Comment by sirfarmalot** [comment]
@FKLC I know you might have saw something in instaloader than you feel is better than your source and I know ppl are going to ask you, 'why you are doing this and that, when there is already something "better"', BUT you know what man or woman!!!!! DO YOU!!!!! 

Don't quit NOTHING because of what some ppl say on the internet or in real life. I saw that you were 15 yrs old. That is dope AF for you even to publish a lib on github and humble enough as a dev to engage with ppl in the issues! I SALUTE YOU MAN/WOMAN!!!!! 

DO NOT QUIT DOING ANYTHING BECAUSE OF OTHER PPL COMMENTS! KEEP ROCKING YOUNG (WO)MAN. KEEP INNOVATING AND CREATING. YOU INSPIRE ME TO KEEP GOING!!!

**Comment by FKLC** [comment]
Hey @sirfarmalot thank you for your really kind words. At commit 9c656b4545f6f441e791350d991f09c34e5862e6 I made the library fully modular so anybody who don't even know about Instagram API can implement a feature even if I forget it just by inspecting requests to achieve this.

> IGQL isn't designed to be a CLI or a tool, it is a data collector 

So I checked Instaloader to see if I forget about any feature then I see GraphQL endpoints in source. Which made me felt like stupid so I thought I should say people about Instaloader because it is actually have better API and bigger community which makes Instaloader way too better. And over 1.5 year I'm not using any kind of social media for privacy so this made me think about two things:
1) I'm not even using Instagram so how am I going to know when a new feature came out?
2) I'm not using social media for privacy so why am I letting people collect data even it is public (you can 
even collect private account data if you provide session_id)

Beside of these main reasons this isn't about other people comments. I thought telling people about Instaloader is a must to do. Because you know I could just delete this issue and hide it but this wouldn't worth it. To me open source is not a kind of race. So not mentioning Instaloader would like to stealing people hours instead of helping people I would actually harm them. I know there is a lot of open source sudoku, snake etc.. games which people are actually doing to exercise or to show off their skills but in this situation I'm trying to ease people work so  to me this was the right thing to do.

**Comment by sirfarmalot** [comment]
email me ya addy ill send you a global sim, so you can get faster inet connection.
lmk where in turkey you are so i can send the correct sim/hardware.
st@xperimentalnewmedia.com

**Comment by FKLC** [comment]
Thank you @sirfarmalot but actually internet isn't that slow in Turkey. I wrote that because i don't know what to write there since I'm currently studying. Your offer is so kind but I have to reject it. Thank you again for your interest.
